google_cloud_path = '/home/airflow/is3107/src/test-344015-02e727f034f5.json'
project_id = 'test-344015'
staging_dataset = 'TEST_DWH_STAGING'
dwh_dataset = 'TEST_DWH'
gs_bucket = 'is3107_bucket_test'
model_path = '/home/airflow/dags/sentiment_model/model.pickle'
vectorizer_path = '/home/airflow/dags/sentiment_model/vectorizer.pickle'
alert_email_receipient = ''